apiVersion: v1
kind: Secret
metadata:
  name:  pubmed-secret
  namespace: reciter
  labels:
    app: reciter-pubmed
    environment: dev
    owner: szd2013
stringData:
  PUBMED_API_KEY: <<pubmed-api-key>>
type: Opaque